proxy:
  defaultInboundPolicy: "audit"
  nativeSidecar: true
identity:
  # -- If the linkerd-identity-trust-roots ConfigMap has already been created
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
